server/core/urls.py
# Author: Adrian Kiraly <xkiral01@stud.fit.vutbr.cz>
# [original]
# Last change: 2017-11-03

from django.conf.urls import url

from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.sensor_list, name='sensors'),
    url(r'^sensor/(?P<pk>\d+)/$', views.SensorView.as_view(), name='sensor'),
    url(r'^sensor/(?P<pk>\d+)/page/(?P<page>\d+)/$', views.SensorView.as_view(), name='sensor_page'),
    url(r'^sensor/(?P<pk>\d+)/graph/$', views.GraphView.as_view(), name='graph'),
    # API endpoints
    url(r'^api/ping/$', views.api_ping, name='api_ping'),
    url(r'^api/first-contact/$', views.api_firstcontact, name='api_firstcontact'),
    url(r'^api/measurement/$', views.api_measurement, name='api_measurement'),
    url(r'^api/sensor/(?P<pk>\d+)/csv/$', views.api_sensor_csv, name='api_sensor_csv'),
]

server/server/urls.py
# Author: Adrian Kiraly <xkiral01@stud.fit.vutbr.cz>
# Changes
# - Included core url patterns
# Last change: 2017-11-02

"""server URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls'))
]

server/core/models.py
# Author: Adrian Kiraly <xkiral01@stud.fit.vutbr.cz>
# [original]
# Last change: 2017-11-03

from django.db import models

# Create your models here.
from django.utils import timezone


class Sensor(models.Model):
    COLOR_CHOICES = (
        ('is-primary', 'Turquoise'),
        ('is-link', 'Blue'),
        ('is-info', 'Cyan'),
        ('is-success', 'Green'),
        ('is-warning', 'Yellow'),
        ('is-danger', 'Red'),
        ('is-light', 'White'),
        ('is-dark', 'Black'),
    )

    # Identification
    chip_id = models.PositiveIntegerField(unique=True)

    # User supplied info
    name = models.CharField(max_length=256)
    color = models.CharField(max_length=32, choices=COLOR_CHOICES, default=COLOR_CHOICES[0][0])
    location = models.CharField(max_length=256, blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    # OTA Config parameters
    interval = models.PositiveIntegerField(default=60)
    refresh_required = models.BooleanField(default=False, editable=False)

    # HW Info
    boot_time = models.DateTimeField(blank=True, null=True, editable=False)
    cpu_mhz = models.PositiveIntegerField(blank=True, null=True, editable=False)
    sdk_version = models.CharField(max_length=32, blank=True, null=True, editable=False)
    core_version = models.CharField(max_length=32, blank=True, null=True, editable=False)
    reset_info = models.CharField(max_length=512, blank=True, null=True, editable=False)
    firmware_md5 = models.CharField(max_length=32, blank=True, null=True, editable=False)
    firmware_size = models.PositiveIntegerField(blank=True, null=True, editable=False)
    # TODO more stuff

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('core:sensor', args=[str(self.id)])

    def is_online(self):
        if self.boot_time is None:
            return False
        else:
            delta = timezone.now() - self.measurement_set.first().timestamp
            return delta.total_seconds() < (self.interval + 5)


class Measurement(models.Model):
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE, editable=False)
    timestamp = models.DateTimeField(auto_now=True, editable=False)
    temperature = models.DecimalField(max_digits=7, decimal_places=4, editable=False)
    humidity = models.DecimalField(max_digits=8, decimal_places=4, editable=False)
    pressure = models.DecimalField(max_digits=9, decimal_places=4, editable=False)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return "Measurement #{}".format(self.id)

server/core/views.py
# Author: Adrian Kiraly <xkiral01@stud.fit.vutbr.cz>
# [original]
# Last change: 2017-11-03

import csv
import json

from django.db.models import Max, Min, Count, Avg
from django.http import HttpResponse, JsonResponse, StreamingHttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone, formats
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .models import Sensor, Measurement


def sensor_list(request):
    return render(request, 'core/sensors.html', None)


class SensorView(generic.ListView):
    template_name = 'core/sensor.html'
    context_object_name = 'measurements'
    paginate_by = 30

    def get_queryset(self):
        self.sensor = get_object_or_404(Sensor, id=self.kwargs['pk'])
        return Measurement.objects.filter(sensor=self.sensor)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sensor'] = self.sensor

        # Include stats
        context['stats'] = self.sensor.measurement_set.aggregate(
            count=Count('id'),
            min=Min('temperature'),
            max=Max('temperature'),
        )

        delta = timezone.now() - timezone.timedelta(days=1)
        context['stats'].update(self.sensor.measurement_set.filter(timestamp__gte=delta).aggregate(
            avg=Avg('temperature'),
        ))

        return context


class GraphView(generic.DetailView):
    model = Sensor
    template_name = 'core/graph.html'


# API Endpoints

def api_ping(request):
    """Returns simple 200 OK message, only used for connectivity check"""
    return HttpResponse()


@require_POST
@csrf_exempt
def api_firstcontact(request):
    response = {
        'status': 0,
    }

    # Find sensor in db
    try:
        data = json.loads(request.body.decode('utf-8'))
        sensor = Sensor.objects.get(chip_id=data['id'])
    except Exception as e:
        response['status'] = 1
        response['what'] = str(e)
        return JsonResponse(response)

    # Save current hardware info
    sensor.boot_time = timezone.now()
    sensor.cpu_mhz = data.get('cpu')
    sensor.sdk_version = data.get('sdk')
    sensor.core_version = data.get('core')
    sensor.reset_info = data.get('rst')
    sensor.firmware_md5 = data.get('fw')
    sensor.firmware_size = data.get('fws')
    sensor.save()

    # Add interval to response
    response['int'] = sensor.interval

    return JsonResponse(response)


@require_POST
@csrf_exempt
def api_measurement(request):
    response = {
        'status': 0,
    }

    try:
        data = json.loads(request.body.decode('utf-8'))
        sensor = Sensor.objects.get(chip_id=data['id'])
        measurement = Measurement(
            sensor=sensor,
            temperature=data['temp'],
            humidity=data['hum'],
            pressure=data['pres'],
        )
        measurement.save()
    except Exception as e:
        response['status'] = 1
        response['what'] = str(e)
        return JsonResponse(response)

    if sensor.refresh_required:
        response['int'] = sensor.interval
        sensor.refresh_required = False
        sensor.save()

    return JsonResponse(response)


class Echo(object):
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value


def api_sensor_csv(request, pk):
    sensor = get_object_or_404(Sensor, id=pk)
    data =  sensor.measurement_set.all().order_by('timestamp')
    rows = ([formats.date_format(m.timestamp, "Y-m-d H:i:s"), m.temperature, m.humidity, m.pressure] for m in data)

    pseudo_buffer = Echo()
    writer = csv.writer(pseudo_buffer)
    response = StreamingHttpResponse(
        (writer.writerow(row) for row in rows),
        content_type="text/csv"
    )
    response['Content-Disposition'] = 'attachment; filename="sensordata.csv"'
    return response

server/core/templates/core/base.html
{% load static bulma_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    {% block css %}
        {% font_awesome %}
        <link rel="stylesheet" href="{% static 'bulma/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'core/dygraph.css' %}">
        {% block extra_css %}{% endblock extra_css %}
    {% endblock css %}
</head>
<body>

{% block header %}
    <div class="container">
        <nav class="navbar">
            <div class="navbar-brand">
                <a href="{% url 'core:sensors' %}" class="navbar-item">
                    <span class="icon"><i class="fa fa-seedling"></i></span>
                    <strong>FrendMon</strong>
                </a>

                <div class="navbar-burger burger" data-target="navMenu">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>

            <div class="navbar-menu" id="navMenu">
                <div class="navbar-start">
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link" href="{% url 'core:sensors' %}">
                            Sensors
                        </a>
                        <div class="navbar-dropdown is-boxed">
                            {% for sensor in sensors %}
                                <a href="{% url 'core:sensor' sensor.id %}" class="navbar-item">
                                    {{ sensor.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="navbar-end">
                    <a class="navbar-item autoRefreshControl" title="AutoRefresh">
                        <span class="icon">
                            <i class="fa fa-lg fa-refresh"></i>
                        </span>
                        <span class="is-hidden-desktop">AutoRefresh</span>
                    </a>
                    {% if user.is_authenticated %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a href="{% url 'admin:index' %}" class="navbar-link">
                                Admin
                            </a>
                            <div class="navbar-dropdown is-boxed is-right">
                                <a href="{% url 'admin:core_sensor_changelist' %}" class="navbar-item">
                                    Sensors
                                </a>
                                <a href="{% url 'admin:auth_user_changelist' %}" class="navbar-item">
                                    Users
                                </a>
                                <hr class="navbar-divider">
                                <a href="{% url 'admin:logout' %}" class="navbar-item">
                                    Logout
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <a class="navbar-item is-hidden-desktop-only" href="{% url 'admin:login' %}">
                            Admin
                            <span class="icon"><i class="fa fa-lock"></i></span>
                        </a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
{% endblock header %}

<div id="pjaxContainer">
    {% block hero %}{% endblock hero %}

    <section class="section">
        <div class="container">
            {% block messages %}
                {% if messages %}
                    <div class="messages columns is-desktop">
                        <div class="column is-4 is-offset-4">
                            {% for message in messages %}
                                <div class="message {% if message.tags %}is-{{ message.tags }}{% endif %}">
                                    <div class="message-body">{{ message }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            {% endblock messages %}

            {% block content_area %}
                {% block content_title %}{% endblock content_title %}
                {% block content %}{% endblock content %}
            {% endblock content_area %}
        </div>
    </section>

    {% block modal %}{% endblock modal %}
</div>

{% block javascript %}
    <script type="text/javascript" src="{% static 'core/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/jquery.pjax.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/dygraph.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/app.js' %}"></script>
{% endblock javascript %}
</body>
</html>

server/core/templates/core/graph.html
{% extends 'core/sensorpage_base.html' %}
{% load static %}

{% block title %}{{ sensor.name }}{% endblock %}

{% block content %}
<div class="notification is-info" id="graph-loading-progress">
    <div class="level">
        <div class="level-left">
            <span class="icon is-medium level-item"><i class="fa fa-2x fa-circle-o-notch fa-spin"></i></span>
            <h3 class="title is-4">Loading historic data...</h3>
        </div>
    </div>
</div>
<div class="buttons graph-toggles">
    <div class="graph-toggle-group">
        <input type="checkbox" checked id="0">
        <button class="button {{ sensor.color }} is-light" id="gt-0">
            <label for="0">
                <span class="icon"><i class="far"></i></span>
                <span>Temperature</span>
            </label>
        </button>
    </div>
    <div class="graph-toggle-group">
        <input type="checkbox" checked id="1">
        <button class="button {{ sensor.color }} is-light" id="gt-1">
            <label for="1">
                <span class="icon"><i class="far"></i></span>
                <span>Humidity</span>
            </label>
        </button>
    </div>
    <div class="graph-toggle-group">
        <input type="checkbox" checked id="2">
        <button class="button {{ sensor.color }} is-light" id="gt-2">
            <label for="2">
                <span class="icon"><i class="far"></i></span>
                <span>Pressure</span>
            </label>
        </button>
    </div>
</div>
<div id="graph" style="width: 100%; height: 80vh; max-height: 640px"></div>
<script type="text/javascript">
window.dygraphStart = function () {
    g = new Dygraph(
        document.getElementById("graph"),
        "{% url 'core:api_sensor_csv' sensor.id %}",
        {
            rollPeriod: 7,
            showRoller: true,
            labels: ["Date", "Temperature", "Humidity", "Pressure"],
            xlabel: "Time (UTC)",
            ylabel: "Temperature (C)",
            visibility: [true, true, false]
        }
    );

    g.ready(function () {
        document.getElementById("graph-loading-progress").style.display = 'none';
        setStatus();
    });

    function setStatus() {
        let visibility = g.visibility();
        for (let i = 0; i < visibility.length; i++) {
            let el = document.querySelector(`#gt-${i} .icon i`);
            if (visibility[i]) {
                el.classList.add('fa-check-square');
                el.classList.remove('fa-square');
            } else {
                el.classList.add('fa-square');
                el.classList.remove('fa-check-square');
            }
        }
    }

    document.querySelectorAll('.graph-toggles input[type="checkbox"]').forEach(function (el) {
        el.onclick = function () {
            g.setVisibility(parseInt(el.id), el.checked);
            setStatus();
        }
    })
};
</script>
<style>
    .graph-toggles input[type="checkbox"] {
        display: none;
    }

    .graph-toggle-group {
        margin-right: 10px;
    }

    .dygraph-legend {
        left: 70px !important;
        right: 0;
        background-color: transparent !important;
        width: auto;
    }
</style>
{% endblock %}

server/core/templates/core/pjax_base.html
<title>{% block head_title_base %}{% block head_title %}{% block title %}{% endblock %}{% endblock %}{% endblock %}</title>

{% block hero %}{% endblock hero %}

<section class="section">
    <div class="container">
        {% block messages %}
            {% if messages %}
                <div class="messages columns is-desktop">
                    <div class="column is-4 is-offset-4">
                        {% for message in messages %}
                            <div class="message {% if message.tags %}is-{{ message.tags }}{% endif %}">
                                <div class="message-body">{{ message }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endblock messages %}

        {% block content_area %}
            {% block content_title %}{% endblock content_title %}
            {% block content %}{% endblock content %}
        {% endblock content_area %}
    </div>
</section>

{% block modal %}{% endblock modal %}

server/core/templates/core/sensor.html
{% extends 'core/sensorpage_base.html' %}
{% load humanize %}

{% block title %}{{ sensor.name }}{% endblock %}

{% block content %}
<div class="level">
    <div class="level-item has-text-centered is-hidden-tablet">
        <div>
            <p class="heading">Current temperature</p>
            <p class="title">{{ sensor.measurement_set.first.temperature|floatformat:3 }} °C</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading">24h average</p>
            <p class="title">{{ stats.avg|floatformat:3 }} °C</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading">Minimum</p>
            <p class="title">{{ stats.min|floatformat:3 }} °C</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading">Maximum</p>
            <p class="title">{{ stats.max|floatformat:3 }} °C</p>
        </div>
    </div>
    <div class="level-item has-text-centered">
        <div>
            <p class="heading">Measurements</p>
            <p class="title">{{ stats.count|intcomma }}</p>
        </div>
    </div>
</div>
<hr>

<div class="columns">
    {# Data table #}
    <div class="column">
        <table class="table is-fullwidth is-hoverable">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>Temperature</th>
                    <th>Humidity</th>
                    <th>Pressure</th>
                </tr>
            </thead>
            <tbody>
            {% for measurement in measurements %}
                <tr>
                    <th>{{ measurement.timestamp }}</th>
                    <td>{{ measurement.temperature }} °C</td>
                    <td>{{ measurement.humidity }} %</td>
                    <td>{{ measurement.pressure }} mBar</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% if is_paginated %}
            <nav class="pagination">
                {% if page_obj.has_previous %}
                    <a href="{% url 'core:sensor_page' sensor.id page_obj.previous_page_number %}" class="pagination-previous">Previous</a>
                {% endif %}
                {% if page_obj.has_next %}
                    <a href="{% url 'core:sensor_page' sensor.id page_obj.next_page_number %}" class="pagination-next">Next page</a>
                {% endif %}
                <ul class="pagination-list">
                </ul>
            </nav>
        {% endif %}
    </div>

    {# Panel #}
    <div class="column is-one-third">
        <div class="panel">
            <p class="panel-heading">
                <span>Sensor info</span>
                {% if sensor.is_online %}
                    <span class="tag is-success is-pulled-right">
                        <span class="icon is-small"><i class="fa fa-check"></i></span>&nbsp;Online
                    </span>
                {% else %}
                    <span class="tag is-danger is-pulled-right">
                        <span class="icon is-small"><i class="fa fa-times"></i></span>&nbsp;Offline
                    </span>
                {% endif %}
            </p>

            <span class="panel-block">
                <span class="panel-icon"><i class="fa fa-sync"></i></span>
                <p>Update interval is <strong>{{ sensor.interval }} second{{ sensor.interval|pluralize }}</strong></p>
            </span>

            <span class="panel-block">
                <span class="panel-icon"><i class="fa fa-history"></i></span>
                <p>Last update received <strong>{{ sensor.measurement_set.first.timestamp|timesince }}</strong> ago</p>
            </span>

            {% if sensor.is_online %}
                <span class="panel-block">
                    <span class="panel-icon"><i class="fa fa-arrow-up"></i></span>
                    <p>Current uptime is <strong>{{ sensor.boot_time|timesince }}</strong></p>
                </span>

                <span class="panel-block">
                    <span class="panel-icon"><i class="fa fa-plug"></i></span>
                    <p>Booted up on <strong>{{ sensor.boot_time }}</strong></p>
                </span>
            {% endif %}

            {% if sensor.latitude and sensor.longitude %}
                <a class="panel-block" target="_blank"
                   href="https://www.google.com/maps/search/?api=1&query={{ sensor.latitude }},{{ sensor.longitude }}">
                    <span class="panel-icon"><i class="fa fa-map-marker"></i></span>
                    <p>{{ sensor.latitude }}, {{ sensor.longitude }}</p>
                </a>
            {% endif %}

            <div class="panel-block">
                <a href="{% url 'admin:core_sensor_change' sensor.id %}" class="button is-link is-outlined is-fullwidth">
                    {% if user.is_authenticated %}
                    Edit in administration
                    {% else %}
                    Log in to edit
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

server/core/templates/core/sensorpage_base.html
{% extends 'core/base.html,core/pjax_base.html'|pjax:request %}
{% load humanize %}

{% block hero %}
<section class="hero is-bold {{ sensor.color }}">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <h1 class="title">{{ sensor.name }}</h1>
                    {% if sensor.location %}
                        <h2 class="subtitle">
                            <span class="icon"><i class="fa fa-map-marker"></i></span> {{ sensor.location }}
                        </h2>
                    {% endif %}
                </div>
                <div class="column is-hidden-mobile">
                    <div class="is-pulled-right has-text-centered">
                        <span class="title">{{ sensor.measurement_set.first.temperature|floatformat:3 }} °C</span>
                        <span class="heading">Current temperature</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hero-foot">
        <nav class="tabs is-boxed">
            <div class="container">
                <ul>
                    {% with request.resolver_match.url_name as url_name %}
                    <li {% if url_name == 'sensor' or url_name == 'sensor_page' %}class="is-active"{% endif %}>
                        <a href="{% url 'core:sensor' sensor.id %}">Overview</a>
                    </li>
                    <li {% if url_name == 'graph' %}class="is-active"{% endif %}>
                        <a href="{% url 'core:graph' sensor.id %}">Graphs</a>
                    </li>
                    {% endwith %}
                </ul>
            </div>
        </nav>
    </div>
</section>
{% endblock %}

server/core/templates/core/sensors.html
{% extends 'core/base.html,core/pjax_base.html'|pjax:request %}

{% block title %}Sensors{% endblock %}

{% block hero %}
<section class="hero is-bold is-info">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <h1 class="title">Sensors</h1>
                </div>
                {% if user.is_authenticated %}
                <div class="column is-hidden-mobile">
                    <a href="{% url 'admin:core_sensor_add' %}" class="button is-pulled-right is-outlined is-inverted is-info">
                        <span class="icon"><i class="fa fa-plus"></i></span>
                        <span>Add sensor</span>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<div class="columns">

{% for sensor in sensors %}
    <div class="column is-one-third">
        <a href="{% url 'core:sensor' sensor.id %}"><div class="notification {{ sensor.color }}">
            <h1 class="title">{{ sensor.measurement_set.first.temperature|floatformat:3 }} °C</h1>
            <h2 class="subtitle">{{ sensor.name }}</h2>
        </div></a>
    </div>

    {% if forloop.counter|divisibleby:3 %}
    </div><div class="columns">
    {% endif %}
{% endfor %}

</div>
{% endblock content %}